# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
 production:
   INDIGO_SECRET_KEY: c7954752783fdbaf7b962ac8e5d0c67e1ecfea8ec3e9b4fd13dea56264f9109776fadb557689c3b5d2b22b7b0f4b2e8c4c7bcc3b8d6e77459eb48e30974f47a7
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
