# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d27108ebb9fec8f0f48d267997616273fe8ba5d56779b857b7d56ddc34c8d7758ccba5f8a244faebddd5d063d03734be9c30c53b27e2684e05e1483428a1696c

test:
  secret_key_base: 059779b7b1ea57ee264c25d95f7c159a1ee71bd767b1e01d10a3e0cb92d2691de10816107daa52f9e77131bc2ad312dfa7ad665eba62efbf566bb7469a12f695

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["INDIGO_SECRET_KEY"] %>
